### PR TITLE
Update to EasyRPG 0.5.2

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by inactive123** [comment]
You tested that this works?

**Comment by RobLoach** [comment]
Was able to run the [TestGame](https://github.com/EasyRPG/TestGame).

**Comment by Ghabry** [comment]
I  recommend to also add the remaining commits of the repo (Allow item usage instead of crash and the 2 battle encounter commits) because they fix regressions found in 0.5.2.

**Comment by RobLoach** [comment]
@Ghabry Is there anything holding back a `0.5.3` tag? My usual rule of thumb is to avoid rolling `master` if at all possible. But I'm down with bringing it in! Thanks.

**Comment by Ghabry** [comment]
Yes, it's summer vacation time. Around July & August we usually don't get many work done. We only fixed these two regressions because they affected almost every game. The next release will be probably in one month, together with a few more small fixes.

**Pull request merged**
